<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_pilih_lokasi</name>
   <tag></tag>
   <elementGuidId>87b8d73f-9980-45fe-adae-ec0c6e085daf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[1]/div/div[1]/div[2]/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[1]/div/div[1]/div[2]/div/div[2]/div/button</value>
   </webElementProperties>
</WebElementEntity>
