<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cari_pasar</name>
   <tag></tag>
   <elementGuidId>57f00148-3167-462f-a410-2086c6ecc893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[1]/div/div[1]/div[2]/div/div[3]/div[2]/div/div/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[1]/div/div[1]/div[2]/div/div[3]/div[2]/div/div/input[1]</value>
   </webElementProperties>
</WebElementEntity>
